workflows:
  aeva-ios:
    name: Aeva iOS
    environment:
      xcode: latest
    scripts:
      - name: Build Aeva
        script: |
          set -e
          xcodebuild -project "Aeva.xcodeproj" -scheme "Aeva" -configuration Release -sdk iphoneos -archivePath "$CM_BUILD_DIR/Aeva.xcarchive" CODE_SIGNING_ALLOWED=NO archive
    artifacts:
      - "$CM_BUILD_DIR/Aeva.xcarchive"
      - /tmp/xcodebuild_logs/*.log
